#!/usr/bin/env python3
"""Bake the planner's ``idle_stand`` primitive into an X2M2 binary.

Output is a flat little-endian binary file consumed by:

  * ``gear_sonic_deploy/scripts/x2_pose_watchdog.py`` (Python; PC2 side)
    -- the split-topology idle fallback watchdog that publishes idle_stand
    frames to the deploy on PC2 loopback whenever the upstream pose
    wire from the laptop goes silent (e.g. wifi drop, laptop crash).

  * ``PklMotionReference::Load`` in
    ``gear_sonic_deploy/src/x2/agi_x2_deploy_onnx_ref/include/reference_motion.hpp``
    (C++; same loader the deploy already uses for ``--motion <x2m2>``
    offline replay). Kept format-compatible so a future native C++
    idle fallback can read the exact same file.

Why a dedicated baker rather than ``export_motion_for_deploy.py``:
  * the planner primitives PKL keys each bin by name and stores
    ``root_rot_xyzw`` (not ``root_rot``), so the generic exporter would
    pick up the wrong dict entry / wrong field name.
  * we apply the SAME 30->50 Hz resample + yaw-align-to-(0, 0) that
    the planner's ``LocalMotionPlanner._start_idle_loop`` applies
    (``gear_sonic.utils.planner.blending``), so the X2M2 file matches
    what the planner streams during IDLE_LOOP and the policy sees one
    consistent idle reference distribution regardless of whether the
    planner is live (planner -> deploy) or the wire went silent and
    the watchdog is filling in (X2M2 -> deploy).

Format spec (mirrors ``export_motion_for_deploy.bake_x2m2`` and
``reference_motion.hpp``)::

    uint32   magic        == 0x58324D32  ("X2M2", little-endian)
    uint32   num_frames
    uint32   num_dofs     (must equal 31)
    double   fps
    for each frame f in [0, num_frames):
        double   joint_pos_mj[31]
        double   root_quat_xyzw[4]

Joint velocity is reconstructed at runtime via finite-diff in the
proxy (matches what the C++ deploy does for ``--motion`` replay), so
we intentionally do NOT serialise qvel here.

Example::

    .venv/bin/python -m gear_sonic_deploy.scripts.bake_idle_stand_x2m2 \\
        --primitives-pkl gear_sonic/data/motions/x2_planner_primitives.pkl \\
        --out gear_sonic_deploy/data/idle_stand.x2m2

``pc2_bringup.sh`` calls this script during PC2 setup and rsyncs the
output to ``${PC2_PREFIX}/data/idle_stand.x2m2`` so the proxy has it
on disk before the deploy ever starts.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Shared wire constants + the watchdog's own replay class, so the clip we
# bake is validated by the exact consumer that will loop it on PC2.
# Lightweight imports only (numpy; scipy is pulled lazily by the
# resample / yaw-align helpers below). No torch / isaaclab.
from gear_sonic.utils.pose_pipeline.fallback import IdleStandReplay  # noqa: E402
from gear_sonic.utils.pose_pipeline.wire import (  # noqa: E402
    DEFAULT_PUB_RATE_HZ,
    NUM_BODY_DOFS,
    X2M2_MAGIC,
    load_x2m2,
)

NUM_DOFS = NUM_BODY_DOFS


def _load_idle_stand_replay(primitives_pkl: Path) -> IdleStandReplay:
    """Load ``idle_stand`` from the planner's primitives PKL.

    The PKL is a ``{bin_name: {dof, root_rot_xyzw, root_trans, fps,
    motion_key, ...}}`` mapping (regenerated by
    ``tools/build_demo_bank_from_upstream.sh``; see manifest/REGENERATE.md).
    ``joblib.load`` keeps the planner's state machine out of the import
    graph.

    Resampling: a 30 fps captured stand clip is upcast with the same
    ``resample_motion_30_to_50hz`` the planner's ``load_primitives_pkl``
    uses, so per-frame timing matches the deploy's 50 Hz control loop
    (the synthesized upstream idle_stand already ships at 50 fps and
    passes through untouched). Then the clip is yaw-aligned so frame 0
    sits at (xy=0, yaw=0), exactly like ``_start_idle_loop`` does
    against the planner's (cur_xy, cur_yaw) = (0, 0) start.
    """
    import joblib

    if not primitives_pkl.is_file():
        raise FileNotFoundError(f"primitives PKL not found: {primitives_pkl}")
    raw = joblib.load(primitives_pkl)
    if not isinstance(raw, dict):
        raise ValueError(
            f"{primitives_pkl}: expected dict at top level, got {type(raw)}"
        )
    if "idle_stand" not in raw:
        raise KeyError(
            f"{primitives_pkl}: 'idle_stand' bin missing -- regenerate the "
            f"primitives with tools/build_demo_bank_from_upstream.sh"
        )
    payload = raw["idle_stand"]
    dof_src = np.asarray(payload["dof"], dtype=np.float32)
    rot_src = np.asarray(payload["root_rot_xyzw"], dtype=np.float32)
    trans_src = np.asarray(payload["root_trans"], dtype=np.float64)
    src_fps = float(payload["fps"])
    target_fps = float(DEFAULT_PUB_RATE_HZ)

    from gear_sonic.utils.planner.blending import (
        resample_motion_30_to_50hz,
        yaw_align_segment,
    )

    if abs(src_fps - target_fps) < 0.5:
        dof_out, rot_out, trans_out = dof_src, rot_src, trans_src
    else:
        dof_out, rot_out, trans_out = resample_motion_30_to_50hz(
            dof_src, rot_src, trans_src, src_fps, target_fps,
        )
    aligned_dof, aligned_rot, _ = yaw_align_segment(
        dof_out, rot_out, trans_out,
        xy_world=np.zeros(2, dtype=np.float64),
        yaw_world=0.0,
    )
    return IdleStandReplay(aligned_dof, aligned_rot)


def bake(primitives_pkl: Path, out_path: Path, fps: float = 50.0) -> None:
    if not primitives_pkl.is_file():
        raise FileNotFoundError(f"primitives PKL not found: {primitives_pkl}")

    print(f"[bake_idle] loading idle_stand from {primitives_pkl} ...", flush=True)
    loop = _load_idle_stand_replay(primitives_pkl)
    # IdleStandReplay stores dof (T, 31) f32 and quat (T, 4) f32, both
    # already resampled to DEFAULT_PUB_RATE_HZ (50 Hz) and yaw-aligned
    # to (xy=0, yaw=0). Promote to f64 for X2M2 (matches the format
    # the C++ PklMotionReference loader and export_motion_for_deploy
    # emit -- consistent across the X2M2 ecosystem).
    dof_f64 = loop._dof.astype(np.float64, copy=False)
    quat_f64 = loop._quat.astype(np.float64, copy=False)
    n_frames = int(dof_f64.shape[0])

    # Sanity: quaternion |q| ~ 1 on first / last frame catches obvious
    # wxyz-vs-xyzw swaps before the deploy parses them and tilts the
    # robot 180 deg.
    for label, q in (("first", quat_f64[0]), ("last", quat_f64[-1])):
        norm = float(np.linalg.norm(q))
        if not (0.95 <= norm <= 1.05):
            raise ValueError(
                f"{label} root_quat_xyzw has |q|={norm:.4f}, expected ~1.0; "
                f"is the primitives PKL really xyzw scipy convention?"
            )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("wb") as f:
        f.write(struct.pack("<III", X2M2_MAGIC, n_frames, NUM_DOFS))
        f.write(struct.pack("<d", float(fps)))
        for i in range(n_frames):
            f.write(dof_f64[i].tobytes(order="C"))
            f.write(quat_f64[i].tobytes(order="C"))

    size = out_path.stat().st_size
    expected = 4 * 3 + 8 + n_frames * (8 * NUM_DOFS + 8 * 4)
    print(
        f"[bake_idle] wrote {out_path}\n"
        f"            num_frames = {n_frames}\n"
        f"            fps        = {fps:g}\n"
        f"            duration   = {n_frames / fps:.2f} s\n"
        f"            bytes      = {size} (expected {expected})",
        flush=True,
    )
    if size != expected:
        raise RuntimeError(
            f"[bake_idle] byte count mismatch ({size} != {expected}) -- "
            "check struct alignment"
        )
    # Round-trip through the watchdog's loader so a bake that the PC2
    # consumer would refuse never reaches the rsync step.
    dof_rt, quat_rt, fps_rt = load_x2m2(out_path)
    if dof_rt.shape != (n_frames, NUM_DOFS) or abs(fps_rt - fps) > 1e-9:
        raise RuntimeError(
            f"[bake_idle] round-trip mismatch: dof {dof_rt.shape} fps {fps_rt}"
        )
    print("[bake_idle] verified: load_x2m2 round-trip OK", flush=True)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--primitives-pkl",
        type=Path,
        default=REPO_ROOT / "gear_sonic" / "data" / "motions" / "x2_planner_primitives.pkl",
        help="Source PKL containing the planner's 'idle_stand' bin "
             "(default: gear_sonic/data/motions/x2_planner_primitives.pkl).",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "gear_sonic_deploy" / "data" / "idle_stand.x2m2",
        help="Output .x2m2 path (default: gear_sonic_deploy/data/idle_stand.x2m2).",
    )
    p.add_argument(
        "--fps",
        type=float,
        default=50.0,
        help="FPS stamped into the X2M2 header (default 50; matches "
             "the deploy control loop and bridge publish rate).",
    )
    args = p.parse_args(argv)
    bake(args.primitives_pkl, args.out, fps=args.fps)
    return 0


if __name__ == "__main__":
    sys.exit(main())
