#!/usr/bin/env bash
# §24 FULL-LOOP SIM on the WORKSTATION -- the PC twin of the robot's
# simtest/run_simstack.sh, so a PC-vs-Jetson trace diff compares the same
# topology rather than two different rigs.
#
# Identical by construction to the Jetson launcher: same planner ONNX, same
# sonic ONNX (md5 ec493de71174), same frozen_g1.yaml -> the same generated
# tuning flags, same robot_env.env, same MJCF, same isolated ports, same
# ROS_DOMAIN_ID=73. What DIFFERS is exactly what the experiment is testing:
# x86_64 vs aarch64, and the container's MuJoCo 3.11 vs the Jetson's 3.12.
#
# The deploy re-execs itself into docker_x2/x2sim, which mounts $HOME at the
# same path inside the container -- so host paths below resolve unchanged.
#
#   run:   ./gear_sonic/scripts/simstack_local.sh
#   drive: ./gear_sonic/scripts/simstack_replay_tape.py --tape <tape.jsonl> ...
#   stop:  ./gear_sonic/scripts/simstack_local.sh --stop
set -eo pipefail          # NOT -u: ROS/conda setup scripts reference unbound vars

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Shipped default model set + tuning preset (gear_sonic_deploy/models/README.md):
# what runs when SIMSTACK_SONIC / SONIC_MODEL / MODEL / SIMSTACK_DUAL_MODEL /
# X2_RITUAL_TUNING are all unset. LFS pointer files (no `git lfs pull`) are
# not usable and fall through to the cache layout below.
SHIPPED_STEM="$REPO/gear_sonic_deploy/models/x2_sonic_v16ft8_45000"
SHIPPED_TUNING="$REPO/gear_sonic_deploy/configs/real_deploy_tuning/trained_gains_s0_inc_waistmc.yaml"
shipped_usable() { [[ -f "$1" ]] && ! head -c 40 "$1" | grep -q 'git-lfs'; }
# Session dir (logs, kplanner tape, archived sessions): SIMSTACK_DIR, default under $SONIC_HOME.
S="${SIMSTACK_DIR:-${SONIC_HOME:-$HOME/.cache/sonic}/simstack_pc}"
# Model cache (MODELS.md): CKPT_ROOT (alias X2_CHECKPOINTS_DIR) defaults to $SONIC_HOME/x2,
# the layout download_from_hf.py fills (sonic_policy/, kplanner_onnx/).
SONIC_X2="${SONIC_X2_MODELS:-${SONIC_HOME:-$HOME/.cache/sonic}/x2}"
CKPT="${CKPT_ROOT:-${X2_CHECKPOINTS_DIR:-$SONIC_X2}}"
# The docker deploy sees $CKPT at /workspace/checkpoints (docker-compose.yml
# mounts $X2_CHECKPOINTS_DIR there); models outside $CKPT are staged into it.
mkdir -p "$CKPT"
export X2_CHECKPOINTS_DIR="$CKPT"
# kplanner interpreter: KPLANNER_PYTHON, else ISAACLAB_PYTHON, else the repo .venv, else python3.
PY="${KPLANNER_PYTHON:-${ISAACLAB_PYTHON:-$REPO/.venv/bin/python}}"
command -v "$PY" >/dev/null 2>&1 || PY="$(command -v python3 || true)"
[[ -n "$PY" ]] || { echo "ERROR: no python interpreter for the kplanner (create $REPO/.venv or set KPLANNER_PYTHON)" >&2; exit 1; }
PY="$(command -v "$PY")"
# Stack interpreter for the host-side helpers (plant gate, pad bridge [pygame],
# provenance check): SONIC_PYTHON overrides; default the repo .venv, else the
# kplanner interpreter above.
VPY="${SONIC_PYTHON:-$REPO/.venv/bin/python}"
command -v "$VPY" >/dev/null 2>&1 || VPY="$PY"
VPY="$(command -v "$VPY")"
# Dance / clip bank for the kplanner + pad bridge (regenerated by tools/build_demo_bank_from_upstream.sh).
DANCES="${KPLANNER_DANCES_DIR:-$REPO/gear_sonic_deploy/data/motions_x2m2/demo_bank}"

POSE_PORT=5656; CMD_PORT=5663; CLIP_PORT=5668; WD_PORT=5658; DEBUG_PORT=5657
DEPLOY_DEBUG_PORT=5659   # deploy's OWN telemetry PUB — 5657 is bound by
                         # kplanner first (host net), so a shared port left
                         # the deploy publisher dead and the whole-body
                         # sender blind (rehearsal fall #2, 2026-08-29)

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then sed -n '2,18p' "$0"; echo "   dry:   $0 --dry-run   (resolve paths, print, exit)"; exit 0; fi
DRY_RUN=0; [[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1
if [[ "${1:-}" == "--stop" ]]; then
  echo "  stopping local sim stack ..."
  pkill -f "pc2_kplanner_onnx.py.*--pub-port $POSE_PORT" && echo "    kplanner stopped" || echo "    kplanner not running"
  pkill -f "x2_pose_watchdog.py.*--downstream-port $WD_PORT" && echo "    watchdog stopped" || echo "    watchdog not running"
  pkill -f "deploy_x2.sh sim"        2>/dev/null && echo "    deploy_x2 stopped"  || true
  pkill -f "x2_mujoco_ros_bridge.py" 2>/dev/null && echo "    bridge stopped"     || true
  pkill -f "pc2_pico_token_servic[e]" 2>/dev/null && echo "    token service stopped" || true
  pkill -f "sim_mirror_viewe[r]" 2>/dev/null && echo "    mirror viewer stopped" || true
  pkill -f "pad_locomotion_bridg[e]" 2>/dev/null && echo "    pad bridge stopped" || true
  # The deploy NODE runs inside docker_x2/x2sim and OUTLIVES its host-side
  # wrapper: killing deploy_x2.sh leaves ros2 + x2_deploy_onnx_ref running,
  # still bound to the isolated ports. A later launch then stacks a second
  # container on the same ROS_DOMAIN_ID and both drive the sim at once, which
  # silently invalidates any A/B (observed 2026-08-26: three concurrent
  # stacks, the "soft_hip" arm actually running baseline gains). Stop the
  # container, then sweep the node.
  for c in $(docker ps -q --filter "name=x2sim" 2>/dev/null); do
    docker stop -t 5 "$c" >/dev/null 2>&1 && echo "    container $c stopped"
  done
  sleep 2
  pkill -9 -f "x2_deploy_onnx_ref" 2>/dev/null && echo "    deploy node swept" || true
  exit 0
fi

# The local tuning file must win over robot_env.env's robot-side path (which
# points at /home/run/...). The profile uses the ":=" idiom, so exporting first
# is enough. Honour a caller-supplied X2_RITUAL_TUNING so A/B arms can be run
# as  X2_RITUAL_TUNING=.../soft_hip.yaml simstack_local.sh  -- an unconditional
# export here silently reverted every arm to the baseline.
# SIM_TUNING_YAML (the composite path's variable, used in every runbook
# command) is honored as an alias — it was silently IGNORED here, so all
# 2026-08-30 rehearsals ran frozen_g1.yaml while the ROBOT whole-body
# session ran bigrun.yaml (robot_env.env default): a deploy-gain mismatch
# between the very sessions being compared. Default = the shipped preset
# trained_gains_s0_inc_waistmc.yaml, matching the robot ritual
# (x2_pc2/robot_env.env.template).
if [[ -z "${X2_RITUAL_TUNING:-}" && -n "${SIM_TUNING_YAML:-}" ]]; then
  X2_RITUAL_TUNING="$SIM_TUNING_YAML"
fi
export X2_RITUAL_TUNING="${X2_RITUAL_TUNING:-$SHIPPED_TUNING}"
# Canonicalize to ABSOLUTE: step [4/4] runs from gear_sonic_deploy/, where a
# repo-relative SIM_TUNING_YAML=gear_sonic_deploy/... breaks mid-launch
# (FileNotFoundError in tuning_yaml_to_sim_flags, 2026-08-30). The early
# existence check at the preflight loop still gates a wrong path loudly.
if [[ "$X2_RITUAL_TUNING" != /* ]]; then
  X2_RITUAL_TUNING="$REPO/$X2_RITUAL_TUNING"
fi
# Sim-only runs may use the shipped template when no per-robot env exists
# (x2_pc2/robot_env.env is per-robot and not committed; the ':=' idiom means
# anything you export beforehand still wins).
_ROBOT_ENV="$REPO/x2_pc2/robot_env.env"
if [[ ! -f "$_ROBOT_ENV" ]]; then
  _ROBOT_ENV="$REPO/x2_pc2/robot_env.env.template"
  echo "  x2_pc2/robot_env.env not found -> sourcing robot_env.env.template (sim defaults)"
fi
# shellcheck disable=SC1090,SC1091
. "$_ROBOT_ENV"
export ROS_LOCALHOST_ONLY=1 ROS_DOMAIN_ID=73

# Self-heal: a relaunch over a live stack used to STACK a second container on
# the same DDS domain — two deploys silently drive one sim (the classic
# 2026-08-26 A/B poisoner; bit the operator again 2026-08-29). Sweep first.
if (( ! DRY_RUN )) && docker ps -q --filter "name=x2sim" 2>/dev/null | grep -q .; then
  echo "  live stack detected — stopping it first (no stacked containers) ..."
  "$0" --stop | sed 's/^/  /'
  sleep 2
fi

MJCF="${SIMSTACK_MJCF:-$REPO/gear_sonic/data/assets/robot_description/mjcf/x2_ultra.xml}"   # SIMSTACK_MJCF: sim-only override (2026-09-15 waist-stop test)
# SONIC pose graph: SIMSTACK_SONIC > SONIC_MODEL > MODEL > shipped set > cache layout.
SONIC="${SIMSTACK_SONIC:-${SONIC_MODEL:-${MODEL:-}}}"
if [[ -z "$SONIC" ]]; then
  if shipped_usable "${SHIPPED_STEM}_g1.onnx"; then
    SONIC="${SHIPPED_STEM}_g1.onnx"
    echo "  no MODEL= -> shipped default pose graph $SONIC"
  else
    SONIC="$SONIC_X2/sonic_policy/x2_sonic_policy.onnx"
  fi
fi
# PLANNER_MODEL (dir or template .onnx) as on the operator command sheet;
# default = the template graph in the SONIC cache (x2_kplanner_template.onnx
# from download_from_hf.py, or x2_planner_template.onnx from an export dir).
planner_graph() {  # planner_graph <dir> -> template graph path (or the x2_planner_ name)
  if [[ -f "$1/x2_planner_template.onnx" ]]; then echo "$1/x2_planner_template.onnx"
  elif [[ -f "$1/x2_kplanner_template.onnx" ]]; then echo "$1/x2_kplanner_template.onnx"
  else echo "$1/x2_planner_template.onnx"; fi
}
if [[ -n "${PLANNER_MODEL:-}" ]]; then
  PM="${PLANNER_MODEL/#\~/$HOME}"
  if [[ -d "$PM" ]]; then PLANNER="$(planner_graph "$PM")"; else PLANNER="$PM"; fi
else
  PLANNER="$(planner_graph "$SONIC_X2/kplanner_onnx")"
fi

# --- whole-body teleop rehearsal (2026-08-29) --------------------------------
# X2_WHOLE_BODY_TELEOP=1 (same env var the ROBOT ritual reads) turns this
# stack into the sim twin of the robot whole-body session: the deploy binary
# runs with --whole-body-teleop + the TOKEN graph and connects DIRECTLY to
# the laptop token sender (pico_token_sender.py, binds *:5574 by default) --
# the identical second command as the robot session. kplanner + pose proxy
# are skipped (v1: tokens own the command slot; hybrid = Phase 2) and the
# pose-ref starvation watchdog stays ON, exactly as the ritual arms it.
WB="${X2_WHOLE_BODY_TELEOP:-0}"
# Legacy token-graph rehearsal: SIMSTACK_TOKEN (+ SIMSTACK_TOKENIZER) must be set
# explicitly (the shipped set's own pair is <stem>_g1_token.onnx /
# <stem>_smpl_tokenizer.onnx); the dual-head path needs neither.
TOKEN_ONNX="${SIMSTACK_TOKEN:-}"
# DEFAULT whole-body path = dual-head: with neither SIMSTACK_DUAL_MODEL nor
# SIMSTACK_TOKEN given, the dual graph that sits next to the pose graph (for
# the shipped set: x2_sonic_v16ft8_45000_dual.onnx). The provenance gate
# below still proves the pairing before anything moves.
if [[ "$WB" == "1" && -z "${SIMSTACK_DUAL_MODEL:-}" && -z "$TOKEN_ONNX" ]]; then
  _SIB_DUAL="${SONIC%_g1.onnx}_dual.onnx"
  if [[ "$_SIB_DUAL" != "$SONIC" ]] && shipped_usable "$_SIB_DUAL"; then
    export SIMSTACK_DUAL_MODEL="$_SIB_DUAL"
    echo "  no SIMSTACK_DUAL_MODEL= -> dual-head sibling of the pose graph: $_SIB_DUAL"
  fi
fi

if (( DRY_RUN )); then
  echo "=== DRY RUN (nothing launched) ==="
  for f in "$MJCF" "$SONIC" "$PLANNER" "$X2_RITUAL_TUNING" "$PY" "$DANCES" "$REPO/gear_sonic_deploy/data/idle_stand.x2m2" "$REPO/gear_sonic/data/motions/kplanner_idle_anchor_g1teleop_v3.pkl" "$REPO/x2_pc2/pad_bindings.env"; do
    printf "  %-7s %s\n" "$([[ -e "$f" ]] && echo ok || echo MISSING)" "$f"
  done
  echo "  whole-body: X2_WHOLE_BODY_TELEOP=$WB   dual: ${SIMSTACK_DUAL_MODEL:-<none>}   token: ${TOKEN_ONNX:-<none>}   tokenizer: ${SIMSTACK_TOKENIZER:-<auto>}"
  echo "  session dir: $S   ckpt: $CKPT   kplanner python: $PY   stack python: $VPY"
  exit 0
fi
for f in "$MJCF" "$SONIC" "$PLANNER" "$X2_RITUAL_TUNING" "$PY" "$DANCES"; do
  [[ -e "$f" ]] || { echo "MISSING: $f  (models: see MODELS.md; dances: tools/build_demo_bank_from_upstream.sh)" >&2; exit 1; }
done
if [[ "$WB" == "1" && -z "${SIMSTACK_DUAL_MODEL:-}" && -z "$TOKEN_ONNX" ]]; then
  echo "MISSING: whole-body rehearsal needs SIMSTACK_DUAL_MODEL=<*_dual.onnx> or SIMSTACK_TOKEN=<*_token.onnx> (+ SIMSTACK_TOKENIZER)" >&2; exit 1
fi

# Plant consistency gate: the MJCF is the last hand-copy of the plant
# (yaml is the source; training loads it). Refuse to drive the sim off a
# drifted MJCF — that is exactly the silent mis-scale class from
# armature_investigation.md §6-7.
if ! "$VPY" "$REPO/gear_sonic/scripts/check_plant_consistency.py"; then
  echo "  REFUSING LAUNCH: plant copies disagree (see failures above)" >&2
  exit 1
fi

echo "=============================================================="
echo " §24 FULL-LOOP SIM -- WORKSTATION (x86_64, docker x2sim)"
echo "   anchor / plant   : $X2_ANCHOR_ORI_MODE / $X2_PLANT"
echo "   turn / replan    : $KPLANNER_FIXED_TURN_RAD_S rad/s / $KPLANNER_REPLAN_THRESHOLD_FRAMES"
echo "   tuning           : $(basename "$X2_RITUAL_TUNING") (md5 $(md5sum "$X2_RITUAL_TUNING" | cut -c1-8))"
echo "   sonic  md5       : $(md5sum "$SONIC"   | cut -c1-8)"
echo "   planner md5      : $(md5sum "$PLANNER" | cut -c1-8)"
echo "   mjcf   md5       : $(md5sum "$MJCF"    | cut -c1-8)"
echo "   ports (isolated) : planner $POSE_PORT -> watchdog $WD_PORT -> deploy"
echo "                      cmd $CMD_PORT  clip $CLIP_PORT  debug $DEPLOY_DEBUG_PORT (kplanner-own $DEBUG_PORT)"
echo "   DDS domain       : 73"
echo "=============================================================="

mkdir -p "$S/logs"
# Elastic-band force trace from the MuJoCo bridge (band_force.csv) lands next
# to the other session logs.
export X2_BAND_FORCE_LOG_DIR="$S/logs"

# whole-body: kplanner + watchdog STILL RUN (they own pad/e-stop/dances on
# the robot and are the Phase-2 fallback) — only the DEPLOY's pose input is
# repointed at the token sender below.
if [[ "$WB" == "1" ]]; then
  echo "  WHOLE-BODY REHEARSAL: deploy consumes the token sender on :5574;"
  echo "  kplanner/watchdog run as on the robot (pad, e-stop, Phase-2 fallback)."
  echo "  START THE SENDER (second command, if not already running):"
  echo "    ./gear_sonic/scripts/run_pico_teleop.sh          (no --pc2-host = this sim stack)"
fi
# Corpus capture (2026-09-04): every sim session's SONIC output (csv + flight
# rings + logs) is archived under $S/sessions/<stamp of the previous
# session>/ before this launch overwrites $S/logs -- no operator action.
if [[ -f "$S/logs/joint_pos.csv" ]]; then
  ARCH="$S/sessions/$(date -r "$S/logs/joint_pos.csv" +%Y%m%d_%H%M%S)"
  mkdir -p "$ARCH"
  for f in joint_pos.csv target_pos.csv joint_vel.csv imu.csv action_il.csv tick.csv deploy.log kplanner.log watchdog.log; do
    [[ -f "$S/logs/$f" ]] && mv "$S/logs/$f" "$ARCH/" 2>/dev/null || true
  done
  mv "$S"/logs/flight_*.json "$S"/logs/flight_*.bin "$ARCH/" 2>/dev/null || true
  echo "      previous session archived -> $ARCH ($(du -sh "$ARCH" | cut -f1))"
fi
echo "[1/4] kplanner ..."
# Whole-body release stability (branch stability, 2026-09-04): the sim
# stack runs the kplanner shadow/hold/return state machine by default so
# every rehearsal exercises it; the robot opts in via robot_env.env.
export KPLANNER_WB_RETURN="${KPLANNER_WB_RETURN:-1}"
# kplanner served-frame tape (corpus material, 2026-09-05): persistent per
# launch under the sim stack dir instead of the /tmp fallback the kplanner
# picks when the repo has no log/ dir.
export KPLANNER_TAPE_DIR="${KPLANNER_TAPE_DIR:-$S/kplanner_tape}"
# Dual-head deploy holds the legs itself on a link drop (layer A); the
# kplanner must then HOLD too (frozen at measured) and only RETURN on a pad
# intent -- that return is the deploy's hand-over signal.
if [[ -n "${SIMSTACK_DUAL_MODEL:-}" ]]; then
  export KPLANNER_WB_HOLD_LEGS="${KPLANNER_WB_HOLD_LEGS:-1}"
fi
nohup "$PY" "$REPO/gear_sonic/scripts/pc2_kplanner_onnx.py" \
  --onnx "$PLANNER" --planner-mode "${KPLANNER_MODE:-slow_walk}" --cmd-bind \
  --replan-threshold-frames "${KPLANNER_REPLAN_THRESHOLD_FRAMES:?}" \
  --warmup-qpos "$REPO/gear_sonic/data/motions/kplanner_idle_anchor_g1teleop_v3.pkl" \
  --dances-dir "$DANCES" --ort-gpu \
  --playing-yaw-resync-dps 10 \
  --pub-port "$POSE_PORT" --cmd-port "$CMD_PORT" --clip-cmd-port "$CLIP_PORT" \
  --x2-debug-port "$DEPLOY_DEBUG_PORT" \
  > "$S/logs/kplanner.log" 2>&1 &
echo "      pid $! (log: $S/logs/kplanner.log)"
sleep 12

echo "[2/4] pose watchdog ..."
nohup "$PY" "$REPO/gear_sonic_deploy/scripts/x2_pose_watchdog.py" \
  --upstream-host 127.0.0.1 --upstream-port "$POSE_PORT" --upstream-topic pose \
  --downstream-port "$WD_PORT" --downstream-topic pose \
  --idle-x2m2 "$REPO/gear_sonic_deploy/data/idle_stand.x2m2" \
  --idle-stale-ms 100 --idle-mode blend \
  --hold-last-secs 0.05 --blend-secs 0.15 --x2-debug-port "$DEPLOY_DEBUG_PORT" \
  --blend-from "${WATCHDOG_BLEND_FROM:-measured}" \
  --blend-rate-rad-s "${WATCHDOG_BLEND_RATE_RAD_S:-1.0}" \
  > "$S/logs/watchdog.log" 2>&1 &
echo "      pid $! (log: $S/logs/watchdog.log)"
sleep 5

echo "[3/4] pad bridge (sticks -> kplanner planner_cmd) ..."
# The docker simstack runs on ISOLATED ports (cmd 5663, not the composite
# sim's 5563), so the runbook's bare pad commands silently publish to
# nobody — the pad "worked in sim" only on the old composite path
# (operator outage 2026-08-29). The stack owns the bridge now. pygame
# lives in .venv (NOT env_isaaclab), matching the runbook's usage.
pkill -f "pad_locomotion_bridg[e]" 2>/dev/null || true
# Pad semantics come from the SHARED bindings file — the same one the robot
# ritual sources — so sim and robot always feel identical. Only --source
# local (pad on this workstation, no PC2 daemon) and the isolated ports
# differ from the ritual's bridge invocation.
# shellcheck disable=SC1091
. "$REPO/x2_pc2/pad_bindings.env"
if [[ -e /dev/input/js0 ]]; then
  nohup "$VPY" "$REPO/gear_sonic/scripts/pad_locomotion_bridge.py" \
    --source local --port "$CMD_PORT" \
    ${PAD_LOCK_SPEED:+--lock-speed} --deadman "$PAD_DEADMAN" \
    --clip-pkl "$DANCES" \
    --clip-keys "$EASY_DANCES" --clip-keys-b "$COMBAT" \
    --clip-keys-g "$GESTURES" --clip-keys-m "$MEDIUM" \
    --clip-keys-turn "$TURNS" --clip-keys-micro "${MICRO:-}" \
    --clip-key-dpad-up "$PAD_CLIP_DPAD_UP" \
    --clip-port "$CLIP_PORT" \
    > "$S/logs/pad_bridge.log" 2>&1 &
  PAD_PID=$!
  sleep 3
  if kill -0 "$PAD_PID" 2>/dev/null && grep -q "PUB connect" "$S/logs/pad_bridge.log"; then
    echo "      pid $PAD_PID: $(grep -o 'pad: [^;]*' "$S/logs/pad_bridge.log" | head -1)"
  else
    echo "      WARNING: pad bridge died at startup — GAMEPAD WILL NOT DRIVE. Log:"
    tail -4 "$S/logs/pad_bridge.log" | sed 's/^/      | /'
  fi
else
  echo "      no /dev/input/js0 — GAMEPAD NOT CONNECTED, sticks will not drive."
fi

echo "[4/4] deploy (sim, docker) + bridge ..."
cd "$REPO/gear_sonic_deploy"
# Paths that cross into the container must be CONTAINER paths: deploy_x2.sh
# re-execs itself inside docker_x2/x2sim, and its --log-dir guard only accepts
# the persisting bind mounts (/workspace/sonic = repo root, /root = home). Same
# files as the host paths validated above -- just addressed from inside.
C_MJCF="/workspace/sonic/${MJCF#$REPO/}"
# Container path of a model: repo-resident files (the shipped set) are visible
# at /workspace/sonic/...; anything else is staged into $CKPT (the only other
# non-$HOME mount the container sees, at /workspace/checkpoints).
container_model() {  # container_model <host path> -> container path (stages if needed)
  local m="$1"
  if [[ "$m" == "$REPO/"* ]]; then echo "/workspace/sonic/${m#$REPO/}"
  else
    [[ "$m" == "$CKPT/"* ]] || cp -u "$m" "$CKPT/$(basename "$m")"
    echo "/workspace/checkpoints/$(basename "$m")"
  fi
}
C_SONIC="$(container_model "$SONIC")"
VLA_PORT_EFF="$WD_PORT"                    # pad/kplanner chain is ALWAYS primary
WD_DISABLE_ARGS="--deploy-extra-arg --disable-pose-ref-watchdog"
WB_DEPLOY_ARGS=""
# OmniHand in the sim (2026-09-04, Pico path): SIMSTACK_OMNIHAND=1 composes
# X2 + OmniHand in the MuJoCo bridge (same as the Quest planner stack) and
# SUBs the kplanner's pose wire for left/right_hand_joints[10] -- fed by the
# sender's hand_finger_cmd (grips) through the kplanner arm-ingest overlay.
OMNIHAND_ARGS=""
MJCF_ARGS="--sim-mjcf $C_MJCF"
if [[ "${SIMSTACK_OMNIHAND:-0}" == "1" ]]; then
  # The bridge composes ONLY when no --mjcf is given (an explicit --mjcf
  # must already contain the hand joints; first attempt 2026-09-04 16:25
  # died on exactly that). The composer's base IS this same x2_ultra.xml
  # (compose_x2_with_omnihand.build_x2_with_omnihand_spec), which the
  # plant-consistency gate above already validated -- so drop --sim-mjcf.
  OMNIHAND_ARGS="--sim-with-omnihand --sim-hand-zmq-host 127.0.0.1 --sim-hand-zmq-port $POSE_PORT --sim-hand-zmq-topic pose"
  MJCF_ARGS=""
  echo "      OmniHand: composed in the sim from $(basename "$MJCF"); fingers from the pose wire :$POSE_PORT (sender grips -> hand_finger_cmd :5572)"
fi
if [[ "$WB" == "1" && -n "${SIMSTACK_DUAL_MODEL:-}" ]]; then
  # NATIVE DUAL-HEAD (2026-09-04): ONE SONIC session with both reference
  # heads; the deploy consumes the laptop's SMPL intent stream itself
  # (binds :5573, exactly where the token service used to listen, so
  # run_pico_teleop.sh's local-stack auto-detect keeps working). No token
  # service, no tokenizer, no token graph.
  DUAL="${SIMSTACK_DUAL_MODEL/#\~/$HOME}"
  # Provenance gate: the dual graph and the pose graph in the primary slot
  # must come from the SAME .pt (metadata codec_fingerprint). A wrong swap
  # between two trained models is refused here, before anything moves.
  "$VPY" "$REPO/gear_sonic/scripts/onnx_provenance.py" check \
    --pose "$SONIC" --dual "$DUAL" | sed 's/^/      /' || { echo "      FATAL: ONNX provenance check failed (see above)"; exit 1; }
  C_DUAL="$(container_model "$DUAL")"
  WB_DEPLOY_ARGS="--deploy-extra-arg --whole-body-teleop \
    --deploy-extra-arg --dual-model --deploy-extra-arg $C_DUAL \
    --deploy-extra-arg --smpl-intent-port --deploy-extra-arg 5573 \
    --deploy-extra-arg --wb-switch-ramp-s --deploy-extra-arg ${WB_SWITCH_RAMP_S:-0.4} \
    ${TOKEN_SVC_OPERATOR_ROOT_LEVEL:+--deploy-extra-arg --operator-root-level --deploy-extra-arg $TOKEN_SVC_OPERATOR_ROOT_LEVEL}"
  echo "      whole-body DUAL-HEAD: $DUAL (deploy binds the SMPL intent stream on :5573; no token service)"
  echo "      laptop half:  ./gear_sonic/scripts/run_pico_teleop.sh          (no --pc2-host = this sim stack)"
elif [[ "$WB" == "1" ]]; then
  # HYBRID overlay (Quest-split): pc2_pico_token_service runs HERE (the
  # sim's "robot side"), consuming the deploy debug echo locally and the
  # laptop's intent stream; the deploy reads tokens from localhost:5574.
  C_TOKEN="$(container_model "$TOKEN_ONNX")"
  TOKENIZER_ONNX="${SIMSTACK_TOKENIZER:-${TOKEN_ONNX%_g1_token.onnx}_smpl_tokenizer.onnx}"
  [[ -f "$TOKENIZER_ONNX" ]] || { echo "      FATAL: tokenizer graph not found: $TOKENIZER_ONNX (set SIMSTACK_TOKENIZER)"; exit 1; }
  # Provenance gate (legacy token path): stamped graphs must share one
  # checkpoint; unstamped pre-native exports only warn.
  "$VPY" "$REPO/gear_sonic/scripts/onnx_provenance.py" check \
    --pose "$SONIC" --token "$TOKEN_ONNX" --tokenizer "$TOKENIZER_ONNX" | sed 's/^/      /' || { echo "      FATAL: ONNX provenance check failed (see above)"; exit 1; }
  WB_DEPLOY_ARGS="--deploy-extra-arg --whole-body-teleop \
    --deploy-extra-arg --token-model --deploy-extra-arg $C_TOKEN \
    --deploy-extra-arg --token-zmq-host --deploy-extra-arg 127.0.0.1 \
    --deploy-extra-arg --token-zmq-port --deploy-extra-arg 5574"
  if [[ "${SIMSTACK_NO_TOKEN_SERVICE:-0}" == "1" ]]; then
    echo "      whole-body overlay: token service SKIPPED (SIMSTACK_NO_TOKEN_SERVICE=1 — bisect mode, external :5574 publisher expected)"
  else
  # Kill any stale service AND wait for it to release :5574/:5573 — spawning
  # immediately after pkill races the port release: the fresh service dies on
  # EADDRINUSE while the dying one keeps writing the same log, so the round
  # silently runs OLD service code (rehearsal falls #3/#4, 2026-08-29).
  pkill -f "pc2_pico_token_servic[e]" 2>/dev/null || true
  for _ in $(seq 1 25); do
    ss -tln 2>/dev/null | grep -qE ':5574 |:5573 ' || break
    sleep 0.2
  done
  if ss -tln 2>/dev/null | grep -qE ':5574 |:5573 '; then
    echo "      FATAL: ports 5574/5573 still bound after stale-service sweep"; exit 1
  fi
  nohup "$PY" "$REPO/gear_sonic/scripts/pc2_pico_token_service.py" \
    --tokenizer "$TOKENIZER_ONNX" --debug-port "$DEPLOY_DEBUG_PORT" \
    --planner-cmd-port "$CMD_PORT" \
    ${TOKEN_SVC_OPERATOR_ROOT_LEVEL:+--operator-root-level "$TOKEN_SVC_OPERATOR_ROOT_LEVEL"} \
    ${TOKEN_SVC_OPERATOR_LEAN_CAP:+--operator-lean-cap "$TOKEN_SVC_OPERATOR_LEAN_CAP"} ${TOKEN_SVC_OPERATOR_REACH_CAP:+--operator-reach-cap "$TOKEN_SVC_OPERATOR_REACH_CAP"} \
    > "$S/logs/token_service.log" 2>&1 &
  TOKEN_SVC_PID=$!
  sleep 1.5
  if ! kill -0 "$TOKEN_SVC_PID" 2>/dev/null; then
    echo "      FATAL: token service died at startup — log follows:"
    sed 's/^/      | /' "$S/logs/token_service.log"
    exit 1
  fi
  echo "      whole-body overlay: token service pid $TOKEN_SVC_PID (log: $S/logs/token_service.log)"
  echo "      laptop half:  ./gear_sonic/scripts/run_pico_teleop.sh          (no --pc2-host = this sim stack)"
  fi
fi
# The session dir is only under the repo when SIMSTACK_DIR points there; the
# default ($SONIC_HOME/simstack_pc, i.e. under $HOME) is bind-mounted into the
# container at the same path, so it needs no remapping.
if [[ "$S" == "$REPO/"* ]]; then
  C_LOGS="/workspace/sonic/${S#$REPO/}/logs"
else
  C_LOGS="$S/logs"
fi
TUNING_FLAGS="$(python3 scripts/tuning_yaml_to_sim_flags.py "$X2_RITUAL_TUNING")"
# shellcheck disable=SC2086
nohup ./deploy_x2.sh sim --no-stop-mc --no-confirm \
  ${SIMSTACK_SIM_FLAGS---sim-init-pose stand-settled --sim-no-elastic-band} \
  --autostart-after 8 \
  ${MJCF_ARGS} \
  --model    "$C_SONIC" \
  --vla --vla-zmq-host 127.0.0.1 --vla-zmq-port "$VLA_PORT_EFF" --vla-zmq-topic pose \
  --vla-debug-port "$DEPLOY_DEBUG_PORT" --vla-debug-topic x2_debug \
  --wrist-bypass ik --head-bypass ref --max-target-dev-head 0.40 \
  --log-dir "$C_LOGS" \
  $TUNING_FLAGS \
  ${WD_DISABLE_ARGS} ${WB_DEPLOY_ARGS} ${OMNIHAND_ARGS} ${SIMSTACK_EXTRA_DEPLOY_ARGS:-} \
  --deploy-extra-arg --flight-recorder-seconds --deploy-extra-arg 60 \
  > "$S/logs/deploy.log" 2>&1 &
echo "      pid $! (log: $S/logs/deploy.log)"

# ------------------------------------------------------------------
# Launch verdict — wait until the deploy actually reaches CONTROL (or
# dies) instead of printing "ready" over a corpse. A silent argparse
# death and a viewer-stall E-STOP both hid behind "ready" (2026-08-29).
# ------------------------------------------------------------------
echo "  waiting for deploy verdict (CONTROL vs FATAL, up to 60 s) ..."
VERDICT=""
for _ in $(seq 1 60); do
  if grep -qE "\[FATAL\]|-> SAFE_HOLD" "$S/logs/deploy.log" 2>/dev/null; then
    VERDICT=fatal; break
  fi
  if grep -q "Autostart elapsed" "$S/logs/deploy.log" 2>/dev/null; then
    VERDICT=control; break
  fi
  if ! kill -0 "$(pgrep -f 'deploy_x2.sh sim' | head -1)" 2>/dev/null \
     && ! docker ps -q --filter name=x2sim | grep -q .; then
    VERDICT=dead; break
  fi
  sleep 1
done
case "$VERDICT" in
  control)
    # Deploy is up — now verify the PAD CHAIN armed off its x2_debug echo.
    # The kplanner lazily waits (silent, by design) for the deploy's debug
    # stream; a wiring break leaves it waiting FOREVER while the watchdog
    # holds the stand — pad dead with zero errors anywhere (bit the
    # operator 2026-08-29 after the 5657->5659 debug-port move).
    KP_ARMED=""
    for _ in $(seq 1 20); do
      if grep -qE "rebase ARMED|planner active" "$S/logs/kplanner.log" 2>/dev/null; then
        KP_ARMED=1; break
      fi
      sleep 1
    done
    if [[ -z "$KP_ARMED" ]]; then
      echo "  VERDICT: DEPLOY UP but KPLANNER NEVER ARMED — pad control is DEAD."
      echo "  (kplanner is not receiving the deploy's x2_debug echo — port wiring?)"
      tail -3 "$S/logs/kplanner.log" | sed 's/^/    | /'
      exit 1
    fi
    echo "  VERDICT: deploy in CONTROL + kplanner ARMED — stack is UP, pad live."
    # Host-side mirror viewer (renders from robot_pose/x2_debug telemetry;
    # read-only, cannot stall the sim). The in-container --sim-viewer is
    # GONE: no NV-GLX in docker, and its GL stall E-STOPPED the deploy.
    if [[ "${SIM_VIEWER_ARGS-viewer}" != "" && "${SIMSTACK_NO_VIEWER:-0}" != "1" && -f "$REPO/gear_sonic/scripts/sim_mirror_viewer.py" ]]; then
      VIEWER_HAND_ARGS=""
      [[ "${SIMSTACK_OMNIHAND:-0}" == "1" ]] && VIEWER_HAND_ARGS="--with-omnihand --hand-pose-port $POSE_PORT"
      nohup "$PY" "$REPO/gear_sonic/scripts/sim_mirror_viewer.py" \
        --debug-port "$DEPLOY_DEBUG_PORT" ${VIEWER_HAND_ARGS} \
        > "$S/logs/mirror_viewer.log" 2>&1 &
      echo "  mirror viewer pid $! (host GL; closing it never affects the sim)"
    fi
    ;;
  fatal)
    echo "  VERDICT: DEPLOY TRIPPED — last fatal lines:"
    grep -E "\[FATAL\]|-> SAFE_HOLD|E-STOP ->" "$S/logs/deploy.log" | tail -3 | sed 's/^/    | /'
    echo "  full log: $S/logs/deploy.log"
    exit 1
    ;;
  dead)
    echo "  VERDICT: DEPLOY DIED BEFORE CONTROL — log tail:"
    tail -12 "$S/logs/deploy.log" | sed 's/^/    | /'
    exit 1
    ;;
  *)
    echo "  VERDICT: no CONTROL after 60 s — log tail:"
    tail -12 "$S/logs/deploy.log" | sed 's/^/    | /'
    exit 1
    ;;
esac
echo "  ready. stop with: $0 --stop"
