#!/usr/bin/env bash
# autogenerated by x2_pc2_daemons.sh for tmux session: x2_hand_bridge
# regenerated on every 'start'; edit the daemon script, not this file
_keep_alive() {
    local rc=$?
    echo
    echo "[tmux-launch] cmd exited with status=${rc}"
    if [[ "${rc}" -ne 0 ]]; then
        echo "[tmux-launch] NON-ZERO EXIT -- inspect scrollback above for the real error."
    fi
    echo "[tmux-launch] keeping pane alive (read scrollback above; Ctrl-D to close)"
    exec bash -l
}
trap _keep_alive EXIT
echo "[tmux-launch] session=${TMUX_PANE:-?} pid=$$"
echo "[tmux-launch] starting at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "[tmux-launch] ---- daemon body ----"
source /opt/ros/humble/setup.bash &&         export AMENT_PREFIX_PATH=/agibot/software/housekeeper/bin/aimdk_msgs:$AMENT_PREFIX_PATH &&         export LD_LIBRARY_PATH=/agibot/software/housekeeper/bin/aimdk_msgs/lib:$LD_LIBRARY_PATH &&         source /home/run/gear-sonic/ws/install/setup.bash &&         export LD_LIBRARY_PATH=/home/run/gear-sonic/onnxruntime/lib:$LD_LIBRARY_PATH &&         export PYTHONPATH=/agibot/software/housekeeper/bin/aimdk_msgs/local/lib/python3.10/dist-packages:/home/run/gear-sonic/ws/src:${PYTHONPATH:-} &&             /home/run/gear-sonic/venv/bin/python3 /home/run/gear-sonic/ws/src/x2/agi_x2_deploy_onnx_ref/scripts/x2_hand_zmq_to_aimdk_bridge.py                 --zmq-host localhost                 --zmq-port 5558                 --zmq-topic pose                 2>&1 | tee -a /home/run/gear-sonic/log/hand_bridge_20260728_194151.log

