/**
 * @file policy_parameters.hpp
 * @brief Motor constants, PID gains, joint mappings, action scales, and default
 *        standing angles for the AgiBot X2 Ultra 31-DOF policy.
 *
 * AUTOGENERATED — DO NOT EDIT BY HAND.
 *
 * Regenerate via:
 *   python gear_sonic_deploy/scripts/codegen_x2_policy_parameters.py
 *
 * Source of truth: gear_sonic/scripts/eval_x2_mujoco.py
 *   - MUJOCO_JOINT_NAMES, IL_TO_MJ_DOF, MJ_TO_IL_DOF
 *   - ARMATURES (per joint family) + NATURAL_FREQ + DAMPING_RATIO
 *   - EFFORT_LIMITS (per joint family)
 *   - DEFAULT_JOINT_POS (training reset pose, MuJoCo joint order)
 *
 * ## Joint Ordering
 *
 * Two ordering conventions coexist:
 *   - **MuJoCo order** — used by the simulator, motion-lib PKLs, and the
 *     X2 robot's URDF kinematic tree.
 *   - **IsaacLab order** — used internally by the trained policy and the
 *     proprioception buffer. The IL ordering interleaves left/right
 *     joints (hip_pitch L/R/.../waist_yaw/...).
 *
 * ``isaaclab_to_mujoco`` and ``mujoco_to_isaaclab`` provide the remapping.
 *
 * ## PID Gain Computation
 *
 * Per-joint stiffness and damping derive from a per-armature
 * critically-damped second-order model:
 *   stiffness = armature * (2 * pi * 10 Hz)^2
 *   damping   = 2 * zeta * armature * (2 * pi * 10 Hz)        (zeta = 2.0)
 *
 * The X2 (unlike the G1) uses joint-keyword-based armature lookup rather
 * than a small fixed motor-type taxonomy, so the per-joint gains are
 * baked in directly below.
 *
 * ## Action Scaling
 *
 * Policy actions are scaled per joint:
 *   action_scale = 0.25 * effort_limit / stiffness
 *
 * Final command: target = action * action_scale + default_angle.
 */

#ifndef POLICY_PARAMETERS_HPP
#define POLICY_PARAMETERS_HPP

#include <array>
#include <cstddef>

// ---------- Robot dimensions ----------
constexpr std::size_t NUM_DOFS = 31;
constexpr std::size_t HISTORY_LEN = 10;
constexpr std::size_t NUM_FUTURE_FRAMES = 10;
constexpr double CONTROL_DT = 0.02;
constexpr double SIM_DT = 0.005;
constexpr int DECIMATION = 4;
constexpr double DT_FUTURE_REF = 0.1;

// ---------- Joint name table (MJCF order; canonical) ----------
const std::array<const char*, 31> mujoco_joint_names = {
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
    "waist_yaw_joint",
    "waist_pitch_joint",
    "waist_roll_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_yaw_joint",
    "left_wrist_pitch_joint",
    "left_wrist_roll_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_yaw_joint",
    "right_wrist_pitch_joint",
    "right_wrist_roll_joint",
    "head_yaw_joint",
    "head_pitch_joint",
};

// ---------- Joint ordering remaps ----------
// IL_TO_MJ_DOF[il_idx] = mj_idx  -> use to send IL-ordered tensors to MJ/SDK
const std::array<int, 31> isaaclab_to_mujoco = {0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 29, 15, 22, 4, 10, 30, 16, 23, 5, 11, 17, 24, 18, 25, 19, 26, 20, 27, 21, 28};
// MJ_TO_IL_DOF[mj_idx] = il_idx  -> use to map robot/MJ readings into IL order
const std::array<int, 31> mujoco_to_isaaclab = {0, 3, 6, 9, 14, 19, 1, 4, 7, 10, 15, 20, 2, 5, 8, 12, 17, 21, 23, 25, 27, 29, 13, 18, 22, 24, 26, 28, 30, 11, 16};

// kp[i] = armature * (2*pi*10 Hz)^2   [plant: vendor_20260823]
inline std::array<double, 31> kps = {          // runtime-overridable (plant_loader, X2_PLANT) since 2026-09-08
    114.80248830, // left_hip_pitch_joint
    114.80248830, // left_hip_roll_joint
    114.80248830, // left_hip_yaw_joint
    114.80248830, // left_knee_joint
    34.89892116, // left_ankle_pitch_joint
    12.36855665, // left_ankle_roll_joint
    114.80248830, // right_hip_pitch_joint
    114.80248830, // right_hip_roll_joint
    114.80248830, // right_hip_yaw_joint
    114.80248830, // right_knee_joint
    34.89892116, // right_ankle_pitch_joint
    12.36855665, // right_ankle_roll_joint
    114.80248830, // waist_yaw_joint
    12.36855665, // waist_pitch_joint
    12.36855665, // waist_roll_joint
    34.89892116, // left_shoulder_pitch_joint
    34.89892116, // left_shoulder_roll_joint
    12.36855665, // left_shoulder_yaw_joint
    12.36855665, // left_elbow_joint
    12.36855665, // left_wrist_yaw_joint
    16.77832748, // left_wrist_pitch_joint
    16.77832748, // left_wrist_roll_joint
    34.89892116, // right_shoulder_pitch_joint
    34.89892116, // right_shoulder_roll_joint
    12.36855665, // right_shoulder_yaw_joint
    12.36855665, // right_elbow_joint
    12.36855665, // right_wrist_yaw_joint
    16.77832748, // right_wrist_pitch_joint
    16.77832748, // right_wrist_roll_joint
    16.77832748, // head_yaw_joint
    16.77832748, // head_pitch_joint
};

// kd[i] = 2 * zeta * armature * (2*pi*10 Hz)   [plant: vendor_20260823]
inline std::array<double, 31> kds = {
    7.30855340, // left_hip_pitch_joint
    7.30855340, // left_hip_roll_joint
    7.30855340, // left_hip_yaw_joint
    7.30855340, // left_knee_joint
    2.22173432, // left_ankle_pitch_joint
    0.78740677, // left_ankle_roll_joint
    7.30855340, // right_hip_pitch_joint
    7.30855340, // right_hip_roll_joint
    7.30855340, // right_hip_yaw_joint
    7.30855340, // right_knee_joint
    2.22173432, // right_ankle_pitch_joint
    0.78740677, // right_ankle_roll_joint
    7.30855340, // waist_yaw_joint
    0.78740677, // waist_pitch_joint
    0.78740677, // waist_roll_joint
    2.22173432, // left_shoulder_pitch_joint
    2.22173432, // left_shoulder_roll_joint
    0.78740677, // left_shoulder_yaw_joint
    0.78740677, // left_elbow_joint
    0.78740677, // left_wrist_yaw_joint
    1.06814150, // left_wrist_pitch_joint
    1.06814150, // left_wrist_roll_joint
    2.22173432, // right_shoulder_pitch_joint
    2.22173432, // right_shoulder_roll_joint
    0.78740677, // right_shoulder_yaw_joint
    0.78740677, // right_elbow_joint
    0.78740677, // right_wrist_yaw_joint
    1.06814150, // right_wrist_pitch_joint
    1.06814150, // right_wrist_roll_joint
    1.06814150, // head_yaw_joint
    1.06814150, // head_pitch_joint
};

// 0.25 * effort / (armature * w^2)   [plant: vendor_20260823]
inline std::array<double, 31> x2_action_scale = {
    0.26131838, // left_hip_pitch_joint
    0.26131838, // left_hip_roll_joint
    0.26131838, // left_hip_yaw_joint
    0.26131838, // left_knee_joint
    0.25788763, // left_ankle_pitch_joint
    0.48510106, // left_ankle_roll_joint
    0.26131838, // right_hip_pitch_joint
    0.26131838, // right_hip_roll_joint
    0.26131838, // right_hip_yaw_joint
    0.26131838, // right_knee_joint
    0.25788763, // right_ankle_pitch_joint
    0.48510106, // right_ankle_roll_joint
    0.26131838, // waist_yaw_joint
    0.48510106, // waist_pitch_joint
    0.48510106, // waist_roll_joint
    0.25788763, // left_shoulder_pitch_joint
    0.25788763, // left_shoulder_roll_joint
    0.48510106, // left_shoulder_yaw_joint
    0.48510106, // left_elbow_joint
    0.48510106, // left_wrist_yaw_joint
    0.08940104, // left_wrist_pitch_joint
    0.08940104, // left_wrist_roll_joint
    0.25788763, // right_shoulder_pitch_joint
    0.25788763, // right_shoulder_roll_joint
    0.48510106, // right_shoulder_yaw_joint
    0.48510106, // right_elbow_joint
    0.48510106, // right_wrist_yaw_joint
    0.08940104, // right_wrist_pitch_joint
    0.08940104, // right_wrist_roll_joint
    0.03874045, // head_yaw_joint
    0.00894010, // head_pitch_joint
};

// default joint positions (rad)   [plant: vendor_20260823]
inline std::array<double, 31> default_angles = {
    -0.31200000, // left_hip_pitch_joint
    0.00000000, // left_hip_roll_joint
    0.00000000, // left_hip_yaw_joint
    0.66900000, // left_knee_joint
    -0.36300000, // left_ankle_pitch_joint
    0.00000000, // left_ankle_roll_joint
    -0.31200000, // right_hip_pitch_joint
    0.00000000, // right_hip_roll_joint
    0.00000000, // right_hip_yaw_joint
    0.66900000, // right_knee_joint
    -0.36300000, // right_ankle_pitch_joint
    0.00000000, // right_ankle_roll_joint
    0.00000000, // waist_yaw_joint
    0.00000000, // waist_pitch_joint
    0.00000000, // waist_roll_joint
    0.20000000, // left_shoulder_pitch_joint
    0.20000000, // left_shoulder_roll_joint
    0.00000000, // left_shoulder_yaw_joint
    -0.60000000, // left_elbow_joint
    0.00000000, // left_wrist_yaw_joint
    0.00000000, // left_wrist_pitch_joint
    0.00000000, // left_wrist_roll_joint
    0.20000000, // right_shoulder_pitch_joint
    -0.20000000, // right_shoulder_roll_joint
    0.00000000, // right_shoulder_yaw_joint
    -0.60000000, // right_elbow_joint
    0.00000000, // right_wrist_yaw_joint
    0.00000000, // right_wrist_pitch_joint
    0.00000000, // right_wrist_roll_joint
    0.00000000, // head_yaw_joint
    0.00000000, // head_pitch_joint
};

#endif // POLICY_PARAMETERS_HPP
